name: 'Terraform destroy PROD'

on:
  push:
    branches:
      - "0"
    paths-ignore:
      - "**"

permissions:
  id-token: write

jobs:
  Terraform:
    name: "Terraform"
    environment: "production"
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4


    # Install the latest version of Terraform CLI and configure the Terraform ration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: cd spoke
      run : cd spoke

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: spoke

    - name: terraform workspace select
      run: terraform workspace select PROD
      working-directory: spoke

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      run: terraform apply -destroy -auto-approve -input=false -var-file=variables/PROD.tfvars -var 'client_secret=${{ secrets.client_secret }}'
      working-directory: spoke


